### PR TITLE
bump ROS version required for ruby 2.3 support

### LINKED ISSUE #1: Support ruby 2.3 by using recursive-open-struct == 1.0.0
@moolitayer I can't use the newer kubeclient with this gem in manageiq because [kubeclient was updated to rely on recursive-open-struct 1.0.0 for ruby 2.3 support](https://github.com/abonas/kubeclient/issues/145).

```
Bundler could not find compatible versions for gem "recursive-open-struct":
  In Gemfile:
    recursive-open-struct (~> 1.0.0)

    image-inspector-client (>= 1.0.0) was resolved to 1.0.0, which depends on
      recursive-open-struct (= 0.6.1)

    kubeclient (= 1.0.0) was resolved to 1.0.0, which depends on
      recursive-open-struct (= 1.0.0)

    kubeclient (= 1.0.0) was resolved to 1.0.0, which depends on
      recursive-open-struct (= 1.0.0)
```

Can you please support 1.0.0+ of recursive-open-struct and release a new version?

Thanks!

### PR DESCRIPTION
**Pull request by moolitayer**
fixes #1

### CODE REVIEW

**Comment by moolitayer** [comment]
@abonas could you review

**Comment by abonas** [comment]
the change itself looks straight forward, 
However I'm completely unfamiliar with this client, so I can't say anything about the impact of the change on the functionality.
(BTW who reviewed the initial client's code?)

**Comment by moolitayer** [comment]
@abonas first commit wan't reviewed. I wanna get reviews going forward.
you can take a look here: https://github.com/moolitayer/image-inspector-client/blob/master/lib/image-inspector-client.rb#L33 .

**Comment by moolitayer** [comment]
ROS [CHANGE LOG](https://github.com/aetherknight/recursive-open-struct/blob/master/CHANGELOG.md)

**Comment by moolitayer** [comment]
@simon3z @zeari please review

**Comment by simon3z** [comment]
@moolitayer is this covered by tests? If not we should have tests. Also enable travis so we'll know if this breaks something.

**Comment by jrafanie** [comment]
Thanks for working on this @moolitayer @simon3z @abonas :heart:

**Comment by moolitayer** [comment]
@simon3z enabled travis. There is a [test case that covers ROS creation](https://github.com/moolitayer/image-inspector-client/blob/master/test/test_metadata.rb#L14)

**Comment by moolitayer** [comment]
@jrafanie @abonas my pleasure, we need a patch at miq bumping versions of: openshift-client, kubeclient, image-inspector-client toghether

**Comment by simon3z** [comment]
> @simon3z enabled travis. There is a test case that covers ROS creation

If we have a good test coverage and travis is green (which seems to be the case), then it's a :+1:  for me.

**Pull request merged**
